### ISSUE TITLE
Fix documentation for running as desktop application, or wait for new tauri release

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#115]
```
➜  ustaxes git:(master) yarn desktop
yarn run v1.22.10
$ node ./setup.js && tauri dev
[tauri]: running dev
NOT SUPPORTED: option format. `validateFormats: false` can be used instead.
NOT SUPPORTED: option nullable. "nullable" keyword is supported by default.
NOT SUPPORTED: option uniqueItems. "uniqueItems" keyword is always validated.
DEPRECATED: option unicode. "minLength"/"maxLength" account for unicode characters by default.
(node:21125) UnhandledPromiseRejectionWarning: Error: strict mode: unknown keyword: "defaultProperties"
    at Object.checkStrictMode (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/validate/index.js:183:15)
    at Object.checkUnknownRules (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/util.js:32:24)
    at checkKeywords (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/validate/index.js:118:12)
    at Object.validateFunctionCode (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/validate/index.js:14:9)
    at Ajv.compileSchema (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/index.js:78:20)
    at Ajv._compileSchemaEnv (/home/projects/oss/ustaxes/node_modules/ajv/dist/core.js:444:37)
    at Ajv.compile (/home/projects/oss/ustaxes/node_modules/ajv/dist/core.js:139:38)
    at Object../src/types/config.validator.ts (/home/projects/oss/ustaxes/node_modules/tauri/dist/api/dev.js:1665:37)
    at __webpack_require__ (/home/projects/oss/ustaxes/node_modules/tauri/dist/api/dev.js:1910:42)
    at Object../src/helpers/tauri-config.ts (/home/projects/oss/ustaxes/node_modules/tauri/dist/api/dev.js:446:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.36s.
```

**Comment by zakpatterson** [comment]
This is fixed in tauri's main branch, and I think a release is coming soon. They moved their CLI to compile and run natively instead 
of via node, so it is extremely fast. 

A release is coming soon from tauri, but for now you can:

```
git clone github:tauri-apps/tauri
cd ./tauri/cli/core
cargo install --path . 
```
Assuming `$HOME/.cargo/bin` is on your path
```
cd $your_project_dir
cargo tauri dev
```
