### ISSUE TITLE
Random failures in unit tests

### ISSUE THREAD

**Issue by zakpatterson** [ustaxes/UsTaxes#588]
This failure happens about 40% of the time on CI only and can often be passed by just rerunning the job. 

```
Run npm test

> ustaxes@0.1.11 test /home/runner/work/UsTaxes/UsTaxes
> node ./setup.js && craco test

The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)

/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom.development.js:3905
      var evt = document.createEvent('Event');
                         ^

TypeError: Cannot read property 'createEvent' of null
    at Object.invokeGuardedCallbackDev (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom.development.js:3905:26)
    at invokeGuardedCallback (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom.development.js:23543:11)
    at unstable_runWithPriority (/home/runner/work/UsTaxes/UsTaxes/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at Object.<anonymous>.flushWork (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
    at Immediate.<anonymous> (/home/runner/work/UsTaxes/UsTaxes/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1003:11)
    at processImmediate (internal/timers.js:464:21)
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

**Comment by zakpatterson** [comment]
Again on master branch:

https://github.com/ustaxes/UsTaxes/runs/3779711227

**Comment by zakpatterson** [comment]
Narrowed this down to the `SpouseAndDependent` tests. Multiple `it` statements are executed with asynchronous promises. It seems if one of them fails then the dom will be destroyed. In the middle of that another test that's running will try to access document, causing this error.

**Comment by n8ta** [comment]
If you add an await in front of this getByText you'll see an error

```
# src/tests/components/SpouseAndDependent.test.tsx 
# line 434
    screen.getByText('Sally Brown')
```

```
TestingLibraryElementError: Unable to find an element with the text: Sally Brown. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible
```

I'm not sure how to fix but I think this is the problem.
